language: node_js
sudo: false
node_js:
  - "5"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - openjdk-7-jre

before_script:
  - npm install -g gulp
  - npm install -g bower
  - bower install
  